---
- name: Test APT Package Installation
  hosts: all  # Replace with the hostname or IP of your target host
  become: true             # Use sudo to become root on the target host

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install APT packages
      apt:
        name:
          - nginx
          - git
        state: present

